---
version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:2022.10.1
    steps:
      - checkout
      - run: make pyinit
      - run: make pylint
      - run: make loggy
      - run: make build
      - run: make test TEST_ENV="docker_desktop"
      - run: make pytest

workflows:
  build_and_test:
    jobs:
      - build
