---
version: 2.1

jobs:
  Python_CI:
    machine:
      image: ubuntu-2004:2022.10.1
    steps:
      - checkout
      - run: make python_ci
  Ansible_CI:
    machine:
      image: ubuntu-2004:2022.10.1
    steps:
      - checkout
      - run: make pyinit
      - run: make ansible-lint
  Loggy_CI:
    machine:
      image: ubuntu-2004:2022.10.1
    steps:
      - checkout
      - run: make pyinit
      - run: make loggy
      - run: make loggy-make
      - run: make loggy-test TEST_ENV="docker_desktop"
      - run: make loggy-agent-add
      - run: make loggy-restart
      - run: make loggy-images
      - run: make loggy-ps
      - run: make loggy-stop
      - run: make loggy-start
      - run: make loggy-prune

workflows:
  build_and_test:
    jobs:
      - Python_CI
      - Loggy_CI
