---
version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:2022.10.1
    steps:
      - checkout
      - run: |
          make loggy
          make test TEST_ENV="docker_native"

