---

loggy.deployment.name: loggy_test
kibana.server.name: kibana
kibana.server.host: 0.0.0.0

elasticsearch.hosts: [ https://elasticsearch:9200 ]

elasticsearch.username: kibana_system
elasticsearch.password: ${KIBANA_SYSTEM_PASSWORD}

elasticsearch.ssl.certificateAuthorities: [ config/ca.crt ]
