---
plugin : aws_ec2
aws_access_key: AKIASSWGW7OPWWLCVFY6
aws_secret_key: 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
regions: 
  - eu-central-1
keyed_groups:
  - key: tags
    prefix: tag
  - prefix: instance_type
    key: instance_type
  - key: placement.region
    prefix: aws_region