---
plugin: amazon.aws.aws_ec2
aws_profile: default
regions:
  - eu-central-1
keyed_groups:
  - key: tags
    prefix: tag
  - prefix: instance_type
    key: instance_type
  - key: placement.region
    prefix: aws_region