name: CI-Loggy

on:
  push:
    branches: [ tls, feat_elastic_agent ]
  pull_request:
    branches: [ tls ]

jobs:

  code_linting:
    name: Code linting
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Install dependencies
        run: make pyinit

      - name: Run pylint
        run: make pylint

  test_loggy:
    name: Test suite for the loggy stack
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Install dependencies
        run: make pyinit

      - name: make the loggy stack
        run: make loggy
      
      - name: run tests
        run: make test TEST_ENV="docker_native"

      - name: Run pytest
        run: make pytest

      - name: check the processes
        run: make ps
        ##############
        #            #
        # Tear down. #
        #            #
        ##############
      - name: stop the loggy stack
        run: make prune
