name: CI-Loggy

on:
  push:
    branches: [ tls, feat_make_deployment ]
  pull_request:
    branches: [ tls, loggy ]

jobs:
  python_ci:
    name: Python CI
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        run: |
          sudo apt-get update && \
          sudo apt-get install -y python3 python3-pip python3-venv

      - name: Run Init
        run: make pyinit

      - name: Run Lint
        run: make pylint

      - name: Run Tests
        run: make pytest

      - name: Run Static Type Checking
        run: make type_check

      - name: Run CI Target
        run: make python_ci

  test_loggy:
    name: Test suite for the loggy stack
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        run: |
          sudo apt-get update && \
          sudo apt-get install -y python3 python3-pip python3-venv

      - name: Run Init
        # This is installing the python dependencies.
        run: make pyinit
      
      - name: make loggy
        # This is just printing the help of the loggy python module.
        run: make loggy
      
      - name: make loggy-make
        # This spins up the loggy stack.
        run: make loggy-make
      
      - name: make loggy-ps
        # This checks the processes.
        run: make loggy-ps
      
      - name: make loggy-restart
        # This restarts the loggy stack.
        run: make loggy-restart

      - name: make loggy-images
        # This shows all related images.
        run: make loggy-images

      - name: run tests
        run: make loggy-test TEST_ENV="docker_native"

      - name: check the processes
        run: make loggy-ps
        ##############
        #            #
        # Tear down. #
        #            #
        ##############
      - name: stop the loggy stack
        run: make loggy-stop

      - name: start the loggy stack
        run: make loggy-start

      - name: prune the loggy stack
        run: make loggy-prune
